CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    email VARCHAR(100) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    pin VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP
);