FROM golang:1.26.2-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .
# COPY .env .

RUN go build -o server ./cmd/main.go

FROM alpine:3.22.4
WORKDIR /app

COPY --from=builder /app/server ./
# COPY --from=builder /app/.env ./
# ARG APP_PORT
# ARG JWT_SECRET
# ARG POSTGRES_HOST
# ARG POSTGRES_USER
# ARG POSTGRES_PASSWORD
# ARG POSTGRES_DB
# ARG POSTGRES_PORT
# ARG REDIS_HOST
# ARG REDIS_PORT

# ENV APP_PORT=${APP_PORT}
# ENV JWT_SECRET=${JWT_SECRET}
# ENV POSTGRES_HOST=${POSTGRES_HOST}
# ENV POSTGRES_USER=${POSTGRES_USER}
# ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
# ENV POSTGRES_DB=${POSTGRES_DB}
# ENV POSTGRES_PORT=${POSTGRES_PORT}
# ENV REDIS_HOST=${REDIS_HOST}
# ENV REDIS_PORT=${REDIS_PORT}

CMD ["./server"]